name: Build ZMK firmware
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  matrix:
    runs-on: ubuntu-22.04
    name: Fetch Build Keyboards
    outputs:
      build_matrix: ${{ steps.fetch.outputs.build_matrix }}
      has_valid_build_matrix: ${{ steps.fetch.outputs.has_valid_build_matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Fetch Build Matrix
        id: fetch
        run: |
          matrix_content=$(yq -oj -I0 'build.yaml')
          
          if [ -z "$matrix_content" ] || [ "$matrix_content" = "null" ]; then
            echo "::notice file=build.yaml,title=Empty build matrix file::To add a keyboard to the build, see https://zmk.dev/docs/user-setup#add-a-keyboard."
            echo "has_valid_build_matrix=false" >> $GITHUB_OUTPUT
          else
            echo "build_matrix=$matrix_content" >> $GITHUB_OUTPUT
            echo "has_valid_build_matrix=true" >> $GITHUB_OUTPUT
            echo "$matrix_content"
          fi

  build:
    runs-on: ubuntu-latest
    if: needs.matrix.outputs.has_valid_build_matrix == 'true'
    container:
      image: zmkfirmware/zmk-build-arm:stable
    needs: matrix
    name: Build
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.build_matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build
        run: |
          echo "Building for board: ${{ matrix.board }}"
          echo "Shield: ${{ matrix.shield }}"

  merge:
    runs-on: ubuntu-latest
    needs: build
    name: Merge Output Artifacts
    steps:
      - name: Merge
        run: echo "Merging artifacts"
