name: Build ZMK firmware
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - shield: corne_left
            board: nice_nano_v2
          - shield: corne_right
            board: nice_nano_v2
    steps:
      - run: echo "Building ${{ matrix.shield }} with ${{ matrix.board }}"
